=== DoubleDoorDevelopment/MineTweakerRecipeMaker/src/main/resources/assets/mtrm/MTRM.dtd
<!--
  ~ Copyright (c) 2015 - 2016, Dries007 & Double Door Development
  ~ All rights reserved.
  ~
  ~ Redistribution and use in source and binary forms, with or without
  ~ modification, are permitted provided that the following conditions are met:
  ~
  ~ * Redistributions of source code must retain the above copyright notice, this
  ~   list of conditions and the following disclaimer.
  ~
  ~ * Redistributions in binary form must reproduce the above copyright notice,
  ~   this list of conditions and the following disclaimer in the documentation
  ~   and/or other materials provided with the distribution.
  ~
  ~ THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  ~ AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  ~ IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  ~ DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  ~ FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  ~ DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  ~ SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  ~ CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  ~ OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  ~ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ~
  -->

<!-- MTRM config spec v1.0 - 13 sept 2016 - Dries007 -->
<!ELEMENT MTRM (function|modifier)*>
    <!ATTLIST MTRM name CDATA #REQUIRED><!-- Name for this file. (human readable) -->
    <!ATTLIST MTRM version CDATA #REQUIRED><!-- Internal version. Currently unused. -->
    <!ATTLIST MTRM protocol CDATA #FIXED "1.0"><!-- Protocol version. -->
    <!ELEMENT function (#PCDATA|slot|array|oredictAllowed|number|nbt|string)*><!-- A function call (can technically be anything is displayText in a script file) -->
        <!ATTLIST function name CDATA #REQUIRED><!-- Name for this function. (human readable) -->
        <!ATTLIST function weight CDATA #REQUIRED><!-- Position in the script file. Please use increments of 10! (see vanilla.xml) -->
    <!ELEMENT modifier (#PCDATA|slot|array|oredictAllowed|number|nbt|string)*><!-- A modifier that can be applies to an object -->
        <!ATTLIST modifier name CDATA #REQUIRED><!-- Name for this modifier. (human readable) -->
        <!ATTLIST modifier in (item|ingredient) "item"><!-- The input type -->
        <!ATTLIST modifier out (item|ingredient) "ingredient"><!-- The output type -->

    <!-- Reset indentation because these are used by multiple upper elements -->
    <!ELEMENT array (array|slot|oredictAllowed|number|nbt|string)> <!-- An array of ...-->
        <!ATTLIST array optional (true|false) "false"><!-- true if value can be null -->
        <!ATTLIST array min CDATA "1"><!-- Minimum amount of objects -->
        <!ATTLIST array max CDATA #REQUIRED><!-- Maximum amount of objects -->
    <!ELEMENT nbt EMPTY><!-- A NBT string -->
        <!ATTLIST nbt optional (true|false) "false"><!-- true if value can be null -->
    <!ELEMENT string EMPTY><!-- A normal displayText string -->
        <!ATTLIST string optional (true|false) "false"><!-- true if value can be null -->
    <!ELEMENT number EMPTY><!-- A number -->
        <!ATTLIST number optional (true|false) "false"><!-- true if value can be null -->
        <!ATTLIST number stepsize CDATA "1"><!-- Determines max resolution. Set to 0 for manual entry -->
        <!ATTLIST number min CDATA "0"><!-- Minimum value -->
        <!ATTLIST number max CDATA #IMPLIED><!-- Maximal value. Default is 32767 (max short) -->
        <!ATTLIST number default CDATA #IMPLIED><!-- Default value, if not present, minimum will be used -->
    <!ELEMENT oredictAllowed EMPTY><!-- For when object MUST be an ore dictionary entry -->
        <!ATTLIST oredictAllowed optional (true|false) "false"><!-- true if value can be null -->
        <!ATTLIST stacksizeAllowed stacksizeAllowed (true|false) "false"><!-- true if there can be a stacksizeAllowed -->
    <!ELEMENT slot EMPTY><!-- A (Item or Ingredient) Slot -->
        <!--
            To understand the difference between items and ingredients, read the MineTweaker wiki.
            TLDR: Outputs are items and inputs are often ingredients. Items are a subset of Ingredients.
        -->
        <!ATTLIST slot type (item|ingredient) #REQUIRED>
        <!-- DEFAULTS                                           Item    Ingredient  Explanation -->
        <!ATTLIST slot optional (true|false) #IMPLIED><!--      false   true        true if value can be null -->
        <!ATTLIST slot wildcardAllowed (true|false) #IMPLIED><!--      false   true        true if value can be a wildcardAllowed '<*>' -->
        <!ATTLIST slot metaWildcardAllowed (true|false) #IMPLIED><!--  false   true        true if metadata can be a wildcardAllowed '<mod:item:*>'-->
        <!ATTLIST slot stacksizeAllowed (true|false) #IMPLIED><!--     true    false       true if there can be a stacksizeAllowed here -->
        <!ATTLIST slot oredictAllowed (true|false) #IMPLIED><!--       false   true        true if oredictAllowed is optional here. If oredictAllowed is requred, use oredictAllowed instead of slot-->

=== DoubleDoorDevelopment/MineTweakerRecipeMaker/src/main/resources/assets/mtrm/vanilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2015 - 2017, Dries007 & Double Door Development
  ~ All rights reserved.
  ~
  ~ Redistribution and use in source and binary forms, with or without
  ~ modification, are permitted provided that the following conditions are met:
  ~
  ~ + Redistributions via the Curse or CurseForge platform are not allowed without
  ~   written prior approval.
  ~
  ~ + Redistributions of source code must retain the above copyright notice, this
  ~   list of conditions and the following disclaimer.
  ~
  ~ + Redistributions in binary form must reproduce the above copyright notice,
  ~   this list of conditions and the following disclaimer in the documentation
  ~   and/or other materials provided with the distribution.
  ~
  ~ THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  ~ AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  ~ IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  ~ DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  ~ FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  ~ DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  ~ SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  ~ CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  ~ OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  ~ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ~
  -->

<!DOCTYPE MTRM SYSTEM "mtrm.dtd">
<!-- Vanilla specs - 13 sept 2016 - Dries007 -->
<MTRM version="1" name="Vanilla" protocol="1.0">
    <modifier name="Any damage" out="item">.anyDamage()</modifier>
    <modifier name="With damage" out="item">.anyDamage(<number/>)</modifier>
    <modifier name="With NBT tag" out="item">.withTag(<nbt/>)</modifier>
    <modifier name="Only with NBT tag">.onlyWithTag(<nbt/>)</modifier>
    <modifier name="Only damaged">.onlyDamaged()</modifier>
    <modifier name="Only with n damage">.onlyDamaged(<number/>)</modifier>
    <modifier name="Only with &lt;n damage">.onlyDamageAtLeast(<number/>)</modifier>
    <modifier name="Only with &gt;n damage">.onlyDamageAtMost(<number/>)</modifier>
    <modifier name="Only with &gt;n and &lt;m damage">.onlyDamageBetween(<number/>,<number/>)</modifier>
    <modifier name="Reusable item (no damage)" in="ingredient">.reuse()</modifier>
    <modifier name="Reusable item (1 damage)" in="ingredient">.transformDamage()</modifier>
    <modifier name="Reusable item (custom damage)" in="ingredient">.transformDamage(<number/>)</modifier>
    <modifier name="Replace item" in="ingredient">.transformReplace(<slot type="item"/>)</modifier>
    <modifier name="Don't return item" in="ingredient">.noReturn()</modifier>
    <modifier name="Return item in inventory" in="ingredient">.giveBack(<slot type="item"/>)</modifier>

    <!-- Misc item manipulations. Weight 250 -->
    <function name="Set displayName" weight="250">
        <slot type="item" stacksizeAllowed="false"/>.displayName=<string/>;
    </function>
    <function name="Add tooltip" weight="250">
        <slot type="item"/>.addTooltip(<string/>);
    </function>
    <function name="Add shift tooltip" weight="250">
        <slot type="item"/>.addShiftTooltip(<string/>);
    </function>

    <!-- Ore dictionary. Weight 500 -->
    <function name="Add to ore dictionary entry" weight="500">
        <oredict/>.add(<slot type="item" metaWildcardAllowed="true"/>);
    </function>
    <function name="Remove from ore dictionary entry" weight="500">
        <oredict/>.add(<slot type="item" metaWildcardAllowed="true"/>);
    </function>
    <function name="Mirror ore dictionary to another" weight="500">
        <oredict/>.mirror(<oredict/>);
    </function>
    <function name="Add all ore dictionary entries to another" weight="500">
        <oredict/>.addAll(<oredict/>);
    </function>

    <!-- Crafting -->
    <!-- Removing recipes. Weight 1000 -->
    <function name="Remove all crafting" weight="1000">
        recipes.remove(<slot type="item"/>);
    </function>
    <function name="Remove all shapeless crafting" weight="1000">
        recipes.removeShapeless(<slot type="item"/>);
    </function>
    <function name="Remove all shaped crafting" weight="1000">
        recipes.removeShaped(<slot type="item"/>);
    </function>
    <function name="Remove shapeless crafting" weight="1000">
        recipes.removeShapeless(<slot type="item"/>,<array max="9"><slot type="ingredient"/></array>);
    </function>
    <function name="Remove shaped crafting" weight="1000">
        recipes.removeShaped(<slot type="item"/>,<array max="3"><array max="3"><slot type="ingredient"/></array></array>);
    </function>
    <!-- Adding recipes. weight 1500 -->
    <function name="Add shapeless" weight="1500">
        recipes.addShapeless(<slot type="item"/>,<array max="9"><slot type="ingredient"/></array>);
    </function>
    <function name="Add shaped" weight="1500">
        recipes.addShaped(<slot type="item"/>,<array max="3"><array max="3"><slot type="ingredient"/></array></array>);
    </function>

    <!-- Furnaces -->
    <!-- Removing recipes. Weight 2000 -->
    <function name="Remove furnace recipe" weight="2000">
        furnace.remove(<slot type="ingredient"/>);
    </function>
    <function name="Remove specific furnace recipe" weight="2000">
        furnace.remove(<slot type="item"/>,<slot type="ingredient"/>);
    </function>
    <!-- Adding recipes. Weight 2500 -->
    <function name="Add furnace recipe" weight="2500">
        furnace.addRecipe(<slot type="item"/>,<slot type="ingredient"/>);
    </function>
    <function name="Add furnace recipe with XP" weight="2500">
        furnace.addRecipe(<slot type="item"/>,<slot type="ingredient"/>,<number stepsize="0.01"/>);
    </function>
    <!-- Misc. Weight 2750 -->
    <function name="Set fuel" weight="2750">
        furnace.setFuel(<slot type="ingredient" stacksizeAllowed="false"/>,<number/>);
    </function>

    <!-- Loot tables IDK if / how they work in MT 1.9/1.10, so I'm leavening them out for now
    <function name="Remove loot">
        vanilla.loot.removeChestLoot(<string/>,<slot type="item" wildcardAllowed="true" metaWildcardAllowed="true"/>);
    </function>
    <function name="Add loot">
        vanilla.loot.addChestLoot(<string/>,<slot type="item"/>.weight(<number max="100"/>));
    </function>
    <function name="Add loot, with random stacksizeAllowed">
        vanilla.loot.addChestLoot(<string/>,<slot type="item"/>.weight(<number max="100"/>),<number max="64"/>,<number max="64"/>);
    </function>
    <function name="Remove seeds">
        vanilla.seeds.removeSeed(<slot type="ingredient"/>);
    </function>
    <function name="Add seeds">
        vanilla.seeds.addSeed(<slot type="item"/>.weight(<number max="100"/>));
    </function>-->
</MTRM>
